#!/bin/bash
# Copyright (C) 2023 by Henry Kroll III, www.thenerdshow.com
#
# With code contributions by Matthew Rensberry
#
# This is free software.  You may redistribute it under the terms
# of the Apache license and the GNU General Public License Version
# 2 or at your option any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

export LD_LIBRARY_PATH=/opt/whisper/usr/local/lib:$LD_LIBRARY_PATH
export PATH=$PATH:/opt/whisper/usr/local/bin

export YDOTOOL_SOCKET=/tmp/.ydotool_socket
sudo chmod o+rw $YDOTOOL_SOCKET

# fifo queue to hold temporary audio file names
audio_fifo=$(mktemp); rm "$audio_fifo" ; mkfifo "$audio_fifo"

## create a trap to remove temp files on untimely exit
cleanup() {
    rm -f /tmp/tmp.txt "$audio_fifo"
}
trap cleanup 0

# function to process audio files from queue
trans(){
    while read audio; do
        # transcribe audio
	whisper-cli -m /opt/whisper/models/ggml-base.en.bin -f "$audio" -l en -otxt  --no-prints
        # remove temporary audio file
        rm -f "$audio"
        output="$(<$audio.txt)"; rm -f $audio.txt
        # Type text to terminal, in background
        if [[ ${#output} > 15 ]] || [[ "$output" != "Thanks for watching!" ]] \
            && [[ "$output" != *'['* ]]; then
            ydotool type "$output"
        fi &
    done < "$audio_fifo"
    #cleanup
    rm -f "$audio_fifo"
}

# record audio in background
while true; do
    # Make temporary files to hold audio
    tmp=$(mktemp)
    # Remove it on exit
    trap 'rm "$tmp" ; exit' INT

    # Listen to the mic.
    rec -t wav "$tmp" silence 1 0.1 1% 1 1.0 1%

    # echo temporary audio file name to transcription queue
    echo "$tmp"
done > "$audio_fifo" & #The `&` lets recording run in the background.

# run audio transciption handler
trans
